[functions]
  directory = "netlify/functions"
  external_node_modules = "chatgpt"


[[headers]]
   for = "/*"
   [headers.values]
      Access-Control-Allow-Origin = "*"


[[redirects]]
  from = "/2.2.x/*"
  to = "https://docs.pachyderm.com/archive"
  status = 301
  force = true

[[redirects]]
  from = "/2.1.x/*"
  to = "https://docs.pachyderm.com/archive"
  status = 301
  force = true

