name: Update hpe-branding branch

on:
  push:
    branches:
      - main
    paths:
      - 'content/**'
jobs:
  pull-content-to-hpe:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3
      with:
        ref: main
    - name: Replace "Pachyderm" with "MLDM"
      run: |
        grep -rlZ "Pachyderm" content/ | xargs -0 sed -i 's/Pachyderm/MLDM/g'
    - name: Stash changes 
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git stash
        git fetch
    - name: Checkout hpe-branding branch
      run: |  
        git checkout hpe-branding
        git stash pop
        git commit -ma "Update hpe-branding branch"
        git push --force --quiet https://${{ secrets.HPE }}@github.com/${{ github.repository }} hpe-branding