name: Copy folder to other branch

on:
  push:
    branches:
      - main

jobs:
  copy:
    name: Copy my folder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Replace "Pachyderm" with "MLDM"
        run: |
          cd content
          find . -type f -name "*.md" -exec sed -i -e 's/Pachyderm/MLDM/g' {} +
      - name: Copy files to hpe-branding
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git stash                          # stash any changes to the current branch
          git fetch                          # fetch branches
          git checkout hpe-branding          # checkout to the target branch
          git pull
          git rm -r hpe-branding/content*   # remove the folder
          git add .                    # add updated files to staging area
          git diff-index --quiet HEAD || git commit -am "Update"
          git push origin hpe-branding       # push to remote branch
          git checkout -                      # switch back to the previous branch and unstash changes if any
          git stash pop -q                     # remove the stash if any
