name: PR Checks
on:
  pull_request:
    branches:
      - main

jobs:
  broken-link-check:
    needs: spell-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          fetch-depth: 1
      - uses: ./.github/actions/link-check
        name: Link Check
        env:
          HUGO_OPTIONS: "-b http://localhost:1313/developer" #"--buildDrafts"
          MUFFET_OPTIONS: "-t 30 -e 'https?' " # Excludes external links
